name: Deploy FullStackApp
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    # steps: 
    #   - uses: actions/checkout@v3
      # - name: Use Node.js 20
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20'

      # - name: Checkout code
      #   uses: actions/checkout@v3
      #   with:
      #     ref: v2




      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t kimdonghyun4012/fullstack-docker-app-f ./frontend/Dockerfile.dev ./frontend
      - run: docker run -e CI=true kimdonghyun4012/fullstack-docker-appnpm test

      - run: docker build -t kimdonghyun4012/docker-frontend ./frontend
      - run: docker build -t kimdonghyun4012/docker-nginx ./nginx
      - run: docker build -t kimdonghyun4012/docker-backend ./backend

      - run: docker push kimdonghyun4012/docker-frontend
      - run: docker push kimdonghyun4012/docker-nginx
      - run: docker push kimdonghyun4012/docker-backend

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fullstack-docker-app
          environment_name: Fullstack-docker-app-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-055803798803
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

